prefix: '&b['
suffix: '&b]&3'
blacks:
  - '&r'
  - '&o'
  - '&k'
  - '&l'
  - '&n'
  - '&m'
  - 服主
  - 管理
  - 腐竹
  - 辅助
  - 技术
  - 服务器
  - 客服
  - 种子
  - 老子
  - 爸
  - 妈
  - 爹
  - 傻逼
  - 'null'
  - 
  - 退服
maxLeng: 5